apiVersion: v1
kind: Namespace
metadata:
  name: "persistent-storage"
--- 
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
  namespace: persistent-storage
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
  namespace: persistent-storage  
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 4Gi
---       
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebs-persistent-app
  namespace: persistent-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ebs-persistent-app
  template:
    metadata:
      labels:
        app: ebs-persistent-app
    spec:
      securityContext: 
        seccompProfile:
          type: RuntimeDefault      
      automountServiceAccountToken: false
      containers:
      - name: app
        image: public.ecr.aws/docker/library/busybox:latest
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 60; done"]
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        securityContext:
          capabilities:
            drop:
              - ALL         
        volumeMounts:
        - name: persistent-storage
          mountPath: /data
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: ebs-claim
